name: Daily Commit

on:
  schedule:
    # Runs daily at 00:00 (adjust hours/minutes as needed)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  daily-commit-job:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Add a commit
      - name: Add daily commit - 21f3002753@ds.study.iitm.ac.in
        run: |
          date >> daily-log.txt
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "21f3002753@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Daily commit from GitHub Action"
          git push
